title: Tutorial for the calculation of per-residue contributions to the energy barrier in CP2K 
show_downloads: true
google_analytics:
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
